# Modules PySide

from PySide6.QtCore import QFileInfo
from PySide6.QtGui import QIcon


# List of the avalaible languages on TMDB
LanguageList = [
    { "text": "ab - Abkhazian", "data": "ab", "icon": QIcon("Flags:ab.svg") },
    { "text": "aa - Afar", "data": "aa", "icon": QIcon("Flags:aa.svg") },
    { "text": "af - Afrikaans (Afrikaans)", "data": "af", "icon": QIcon("Flags:af.svg") },
    { "text": "ak - Akan", "data": "ak" }, 
    { "text": "sq - Albanian (shqip)", "data": "sq", "icon": QIcon("Flags:sq.svg") },
    { "text": "am - Amharic", "data": "am" }, 
    { "text": "ar - Arabic (العربية)", "data": "ar" }, 
    { "text": "an - Aragonese", "data": "an", "icon": QIcon("Flags:an.svg") },
    { "text": "hy - Armenian", "data": "hy", "icon": QIcon("Flags:hy.svg") },
    { "text": "as - Assamese", "data": "as", "icon": QIcon("Flags:as.svg") },
    { "text": "av - Avaric", "data": "av", "icon": QIcon("Flags:av.svg") },
    { "text": "ae - Avestan", "data": "ae", "icon": QIcon("Flags:ae.svg") },
    { "text": "ay - Aymara", "data": "ay", "icon": QIcon("Flags:ay.svg") },
    { "text": "az - Azerbaijani (Azərbaycan)", "data": "az", "icon": QIcon("Flags:az.svg") },
    { "text": "bm - Bambara (Bamanankan)", "data": "bm", "icon": QIcon("Flags:bm.svg") },
    { "text": "ba - Bashkir", "data": "ba", "icon": QIcon("Flags:ba.svg") },
    { "text": "eu - Basque (euskera)", "data": "eu", "icon": QIcon("Flags:eu.svg") },
    { "text": "be - Belarusian (беларуская мова)", "data": "be", "icon": QIcon("Flags:be.svg") },
    { "text": "bn - Bengali (বাংলা)", "data": "bn", "icon": QIcon("Flags:bn.svg") },
    { "text": "bi - Bislama", "data": "bi", "icon": QIcon("Flags:bi.svg") },
    { "text": "bs - Bosnian (Bosanski)", "data": "bs", "icon": QIcon("Flags:bs.svg") },
    { "text": "br - Breton", "data": "br", "icon": QIcon("Flags:br.svg") },
    { "text": "bg - Bulgarian (български език)", "data": "bg", "icon": QIcon("Flags:bg.svg") },
    { "text": "my - Burmese", "data": "my", "icon": QIcon("Flags:my.svg") },
    { "text": "cn - Cantonese (广州话 / 廣州話)", "data": "cn", "icon": QIcon("Flags:cn.svg") },
    { "text": "ca - Catalan (Català)", "data": "ca", "icon": QIcon("Flags:ca.svg") },
    { "text": "ch - Chamorro (Finu' Chamorro)", "data": "ch", "icon": QIcon("Flags:ch.svg") },
    { "text": "ce - Chechen", "data": "ce", "icon": QIcon("Flags:ce.svg") },
    { "text": "ny - Chichewa; Nyanja", "data": "ny", "icon": QIcon("Flags:ny.svg") },
    { "text": "cv - Chuvash", "data": "cv", "icon": QIcon("Flags:cv.svg") },
    { "text": "kw - Cornish", "data": "kw", "icon": QIcon("Flags:kw.svg") },
    { "text": "co - Corsican", "data": "co", "icon": QIcon("Flags:co.svg") },
    { "text": "cr - Cree", "data": "cr", "icon": QIcon("Flags:cr.svg") },
    { "text": "hr - Croatian (Hrvatski)", "data": "hr", "icon": QIcon("Flags:hr.svg") },
    { "text": "cs - Czech (Český)", "data": "cs", "icon": QIcon("Flags:cs.svg") },
    { "text": "da - Danish (Dansk)", "data": "da", "icon": QIcon("Flags:da.svg") },
    { "text": "dv - Divehi", "data": "dv", "icon": QIcon("Flags:dv.svg") },
    { "text": "nl - Dutch (Nederlands)", "data": "nl", "icon": QIcon("Flags:nl.svg") },
    { "text": "dz - Dzongkha", "data": "dz", "icon": QIcon("Flags:dz.svg") },
    { "text": "en - English (English)", "data": "en", "icon": QIcon("Flags:en.svg") },
    { "text": "eo - Esperanto (Esperanto)", "data": "eo", "icon": QIcon("Flags:eo.svg") },
    { "text": "et - Estonian (Eesti)", "data": "et", "icon": QIcon("Flags:et.svg") },
    { "text": "ee - Ewe (Èʋegbe)", "data": "ee", "icon": QIcon("Flags:ee.svg") },
    { "text": "fo - Faroese", "data": "fo", "icon": QIcon("Flags:fo.svg") },
    { "text": "fj - Fijian", "data": "fj", "icon": QIcon("Flags:fj.svg") },
    { "text": "fi - Finnish (suomi)", "data": "fi", "icon": QIcon("Flags:fi.svg") },
    { "text": "fr - French (Français)", "data": "fr", "icon": QIcon("Flags:fr.svg") },
    { "text": "fy - Frisian", "data": "fy", "icon": QIcon("Flags:fy.svg") },
    { "text": "ff - Fulah (Fulfulde)", "data": "ff" }, 
    { "text": "gd - Gaelic", "data": "gd", "icon": QIcon("Flags:gd.svg") },
    { "text": "gl - Galician (Galego)", "data": "gl", "icon": QIcon("Flags:gl.svg") },
    { "text": "lg - Ganda", "data": "lg", "icon": QIcon("Flags:lg.svg") },
    { "text": "ka - Georgian (ქართული)", "data": "ka", "icon": QIcon("Flags:ka.svg") },
    { "text": "de - German (Deutsch)", "data": "de", "icon": QIcon("Flags:de.svg") },
    { "text": "el - Greek (ελληνικά)", "data": "el", "icon": QIcon("Flags:el.svg") },
    { "text": "gn - Guarani", "data": "gn" }, 
    { "text": "gu - Gujarati", "data": "gu" }, 
    { "text": "ht - Haitian; Haitian Creole", "data": "ht", "icon": QIcon("Flags:ht.svg") },
    { "text": "ha - Hausa (Hausa)", "data": "ha" }, 
    { "text": "he - Hebrew (עִבְרִית)", "data": "he", "icon": QIcon("Flags:he.svg") },
    { "text": "hz - Herero", "data": "hz", "icon": QIcon("Flags:hz.svg") },
    { "text": "hi - Hindi (हिन्दी)", "data": "hi", "icon": QIcon("Flags:hi.svg") },
    { "text": "ho - Hiri Motu", "data": "ho", "icon": QIcon("Flags:ho.svg") },
    { "text": "hu - Hungarian (Magyar)", "data": "hu", "icon": QIcon("Flags:hu.svg") },
    { "text": "is - Icelandic (Íslenska)", "data": "is", "icon": QIcon("Flags:is.svg") },
    { "text": "io - Ido", "data": "io" }, 
    { "text": "ig - Igbo", "data": "ig", "icon": QIcon("Flags:ig.svg") },
    { "text": "id - Indonesian (Bahasa indonesia)", "data": "id", "icon": QIcon("Flags:id.svg") },
    { "text": "ia - Interlingua", "data": "ia" }, 
    { "text": "ie - Interlingue", "data": "ie" }, 
    { "text": "iu - Inuktitut", "data": "iu", "icon": QIcon("Flags:iu.svg") },
    { "text": "ik - Inupiaq", "data": "ik", "icon": QIcon("Flags:ik.svg") },
    { "text": "ga - Irish (Gaeilge)", "data": "ga", "icon": QIcon("Flags:ga.svg") },
    { "text": "it - Italian (Italiano)", "data": "it", "icon": QIcon("Flags:it.svg") },
    { "text": "ja - Japanese (日本語)", "data": "ja", "icon": QIcon("Flags:ja.svg") },
    { "text": "jv - Javanese", "data": "jv", "icon": QIcon("Flags:jv.svg") },
    { "text": "kl - Kalaallisut", "data": "kl", "icon": QIcon("Flags:kl.svg") },
    { "text": "kn - Kannada (?????)", "data": "kn", "icon": QIcon("Flags:kn.svg") },
    { "text": "kr - Kanuri", "data": "kr", "icon": QIcon("Flags:kr.svg") },
    { "text": "ks - Kashmiri", "data": "ks", "icon": QIcon("Flags:ks.svg") },
    { "text": "kk - Kazakh (қазақ)", "data": "kk", "icon": QIcon("Flags:kk.svg") },
    { "text": "km - Khmer", "data": "km", "icon": QIcon("Flags:km.svg") },
    { "text": "ki - Kikuyu", "data": "ki", "icon": QIcon("Flags:ki.svg") },
    { "text": "rw - Kinyarwanda (Kinyarwanda)", "data": "rw", "icon": QIcon("Flags:rw.svg") },
    { "text": "ky - Kirghiz (??????)", "data": "ky", "icon": QIcon("Flags:ky.svg") },
    { "text": "kv - Komi", "data": "kv", "icon": QIcon("Flags:kv.svg") },
    { "text": "kg - Kongo", "data": "kg", "icon": QIcon("Flags:kg.svg") },
    { "text": "ko - Korean (한국어/조선말)", "data": "ko", "icon": QIcon("Flags:ko.svg") },
    { "text": "kj - Kuanyama", "data": "kj" }, 
    { "text": "ku - Kurdish", "data": "ku", "icon": QIcon("Flags:ku.svg") },
    { "text": "lo - Lao", "data": "lo", "icon": QIcon("Flags:lo.svg") },
    { "text": "la - Latin (Latin)", "data": "la", "icon": QIcon("Flags:la.svg") },
    { "text": "lv - Latvian (Latviešu)", "data": "lv", "icon": QIcon("Flags:lv.svg") },
    { "text": "lb - Letzeburgesch", "data": "lb", "icon": QIcon("Flags:lb.svg") },
    { "text": "li - Limburgish", "data": "li", "icon": QIcon("Flags:li.svg") },
    { "text": "ln - Lingala", "data": "ln" }, 
    { "text": "lt - Lithuanian (Lietuvių)", "data": "lt", "icon": QIcon("Flags:lt.svg") },
    { "text": "lu - Luba-Katanga", "data": "lu", "icon": QIcon("Flags:lu.svg") },
    { "text": "mk - Macedonian", "data": "mk", "icon": QIcon("Flags:mk.svg") },
    { "text": "mg - Malagasy", "data": "mg", "icon": QIcon("Flags:mg.svg") },
    { "text": "ms - Malay (Bahasa melayu)", "data": "ms" }, 
    { "text": "ml - Malayalam", "data": "ml", "icon": QIcon("Flags:ml.svg") },
    { "text": "mt - Maltese (Malti)", "data": "mt", "icon": QIcon("Flags:mt.svg") },
    { "text": "zh - Mandarin (普通话)", "data": "zh", "icon": QIcon("Flags:zh.svg") },
    { "text": "gv - Manx", "data": "gv", "icon": QIcon("Flags:gv.svg") },
    { "text": "mi - Maori", "data": "mi", "icon": QIcon("Flags:mi.svg") },
    { "text": "mr - Marathi", "data": "mr", "icon": QIcon("Flags:mr.svg") },
    { "text": "mh - Marshall", "data": "mh", "icon": QIcon("Flags:mh.svg") },
    { "text": "mo - Moldavian", "data": "mo", "icon": QIcon("Flags:mo.svg") },
    { "text": "mn - Mongolian", "data": "mn", "icon": QIcon("Flags:mn.svg") },
    { "text": "na - Nauru", "data": "na", "icon": QIcon("Flags:na.svg") },
    { "text": "nv - Navajo", "data": "nv" }, 
    { "text": "nr - Ndebele", "data": "nr", "icon": QIcon("Flags:nr.svg") },
    { "text": "nd - Ndebele", "data": "nd", "icon": QIcon("Flags:nd.svg") },
    { "text": "ng - Ndonga", "data": "ng" }, 
    { "text": "ne - Nepali", "data": "ne", "icon": QIcon("Flags:ne.svg") },
    { "text": "xx - No Language (No Language)", "data": "xx" }, 
    { "text": "se - Northern Sami", "data": "se", "icon": QIcon("Flags:se.svg") },
    { "text": "no - Norwegian (Norsk)", "data": "no", "icon": QIcon("Flags:no.svg") },
    { "text": "nb - Norwegian Bokmål (Bokmål)", "data": "nb", "icon": QIcon("Flags:nb.svg") },
    { "text": "nn - Norwegian Nynorsk", "data": "nn", "icon": QIcon("Flags:nn.svg") },
    { "text": "oc - Occitan", "data": "oc" }, 
    { "text": "oj - Ojibwa", "data": "oj" }, 
    { "text": "or - Oriya", "data": "or", "icon": QIcon("Flags:or.svg") },
    { "text": "om - Oromo", "data": "om", "icon": QIcon("Flags:om.svg") },
    { "text": "os - Ossetian; Ossetic", "data": "os", "icon": QIcon("Flags:os.svg") },
    { "text": "pi - Pali", "data": "pi", "icon": QIcon("Flags:pi.svg") },
    { "text": "fa - Persian (فارسی)", "data": "fa", "icon": QIcon("Flags:fa.svg") },
    { "text": "pl - Polish (Polski)", "data": "pl", "icon": QIcon("Flags:pl.svg") },
    { "text": "pt - Portuguese (Português)", "data": "pt", "icon": QIcon("Flags:pt.svg") },
    { "text": "pa - Punjabi (ਪੰਜਾਬੀ)", "data": "pa", "icon": QIcon("Flags:pa.svg") },
    { "text": "ps - Pushto (پښتو)", "data": "ps", "icon": QIcon("Flags:ps.svg") },
    { "text": "qu - Quechua", "data": "qu", "icon": QIcon("Flags:qu.svg") },
    { "text": "rm - Raeto-Romance", "data": "rm", "icon": QIcon("Flags:rm.svg") },
    { "text": "ro - Romanian (Română)", "data": "ro", "icon": QIcon("Flags:ro.svg") },
    { "text": "rn - Rundi (Kirundi)", "data": "rn", "icon": QIcon("Flags:rn.svg") },
    { "text": "ru - Russian (Pусский)", "data": "ru", "icon": QIcon("Flags:ru.svg") },
    { "text": "sm - Samoan", "data": "sm", "icon": QIcon("Flags:sm.svg") },
    { "text": "sg - Sango", "data": "sg", "icon": QIcon("Flags:sg.svg") },
    { "text": "sa - Sanskrit", "data": "sa", "icon": QIcon("Flags:sa.svg") },
    { "text": "sc - Sardinian", "data": "sc", "icon": QIcon("Flags:sc.svg") },
    { "text": "sr - Serbian (Srpski)", "data": "sr", "icon": QIcon("Flags:sr.svg") },
    { "text": "sh - Serbo-Croatian", "data": "sh", "icon": QIcon("Flags:sh.svg") },
    { "text": "sn - Shona", "data": "sn", "icon": QIcon("Flags:sn.svg") },
    { "text": "sd - Sindhi", "data": "sd", "icon": QIcon("Flags:sd.svg") },
    { "text": "si - Sinhalese (සිංහල)", "data": "si", "icon": QIcon("Flags:si.svg") },
    { "text": "cu - Slavic", "data": "cu" }, 
    { "text": "sk - Slovak (Slovenčina)", "data": "sk", "icon": QIcon("Flags:sk.svg") },
    { "text": "sl - Slovenian (Slovenščina)", "data": "sl", "icon": QIcon("Flags:sl.svg") },
    { "text": "so - Somali (Somali)", "data": "so", "icon": QIcon("Flags:so.svg") },
    { "text": "st - Sotho", "data": "st", "icon": QIcon("Flags:st.svg") },
    { "text": "es - Spanish (Español)", "data": "es", "icon": QIcon("Flags:es.svg") },
    { "text": "su - Sundanese", "data": "su", "icon": QIcon("Flags:su.svg") },
    { "text": "sw - Swahili (Kiswahili)", "data": "sw", "icon": QIcon("Flags:sw.svg") },
    { "text": "ss - Swati", "data": "ss", "icon": QIcon("Flags:ss.svg") },
    { "text": "sv - Swedish (svenska)", "data": "sv", "icon": QIcon("Flags:sv.svg") },
    { "text": "tl - Tagalog", "data": "tl", "icon": QIcon("Flags:tl.svg") },
    { "text": "ty - Tahitian", "data": "ty", "icon": QIcon("Flags:ty.svg") },
    { "text": "tg - Tajik", "data": "tg", "icon": QIcon("Flags:tg.svg") },
    { "text": "ta - Tamil (தமிழ்)", "data": "ta" }, 
    { "text": "tt - Tatar", "data": "tt", "icon": QIcon("Flags:tt.svg") },
    { "text": "te - Telugu (తెలుగు)", "data": "te", "icon": QIcon("Flags:te.svg") },
    { "text": "th - Thai (ภาษาไทย)", "data": "th", "icon": QIcon("Flags:th.svg") },
    { "text": "bo - Tibetan", "data": "bo", "icon": QIcon("Flags:bo.svg") },
    { "text": "ti - Tigrinya", "data": "ti", "icon": QIcon("Flags:ti.svg") },
    { "text": "to - Tonga", "data": "to", "icon": QIcon("Flags:to.svg") },
    { "text": "ts - Tsonga", "data": "ts" }, 
    { "text": "tn - Tswana", "data": "tn", "icon": QIcon("Flags:tn.svg") },
    { "text": "tr - Turkish (Türkçe)", "data": "tr", "icon": QIcon("Flags:tr.svg") },
    { "text": "tk - Turkmen", "data": "tk", "icon": QIcon("Flags:tk.svg") },
    { "text": "tw - Twi", "data": "tw", "icon": QIcon("Flags:tw.svg") },
    { "text": "ug - Uighur", "data": "ug", "icon": QIcon("Flags:ug.svg") },
    { "text": "uk - Ukrainian (Український)", "data": "uk", "icon": QIcon("Flags:uk.svg") },
    { "text": "ur - Urdu (اردو)", "data": "ur", "icon": QIcon("Flags:ur.svg") },
    { "text": "uz - Uzbek (ozbek)", "data": "uz", "icon": QIcon("Flags:uz.svg") },
    { "text": "ve - Venda", "data": "ve" }, 
    { "text": "vi - Vietnamese (Tiếng Việt)", "data": "vi", "icon": QIcon("Flags:vi.svg") },
    { "text": "vo - Volapük", "data": "vo" }, 
    { "text": "wa - Walloon", "data": "wa", "icon": QIcon("Flags:wa.svg") },
    { "text": "cy - Welsh (Cymraeg)", "data": "cy", "icon": QIcon("Flags:cy.svg") },
    { "text": "wo - Wolof (Wolof)", "data": "wo", "icon": QIcon("Flags:wo.svg") },
    { "text": "xh - Xhosa", "data": "xh", "icon": QIcon("Flags:xh.svg") },
    { "text": "ii - Yi", "data": "ii", "icon": QIcon("Flags:ii.svg") },
    { "text": "yi - Yiddish", "data": "yi", "icon": QIcon("Flags:yi.svg") },
    { "text": "yo - Yoruba (Èdè Yorùbá)", "data": "yo" }, 
    { "text": "za - Zhuang", "data": "za", "icon": QIcon("Flags:za.svg") },
    { "text": "zu - Zulu (isiZulu)", "data": "zu", "icon": QIcon("Flags:zu.svg") },
]
